removing pad so I can still work with it
When pad is added to the params list, geom_bar errors out 
ggplot(mpg, aes(x=class)) + geom_bar()
Error: Unknown parameters: pad

I don't understand the code enough to understand why.